// Generated by gencpp from file cbf_simulation/state_msg.msg
// DO NOT EDIT!


#ifndef CBF_SIMULATION_MESSAGE_STATE_MSG_H
#define CBF_SIMULATION_MESSAGE_STATE_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cbf_simulation
{
template <class ContainerAllocator>
struct state_msg_
{
  typedef state_msg_<ContainerAllocator> Type;

  state_msg_()
    : id(0)
    , x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)  {
    }
  state_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0.0)
    , y(0.0)
    , vx(0.0)
    , vy(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;





  typedef boost::shared_ptr< ::cbf_simulation::state_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cbf_simulation::state_msg_<ContainerAllocator> const> ConstPtr;

}; // struct state_msg_

typedef ::cbf_simulation::state_msg_<std::allocator<void> > state_msg;

typedef boost::shared_ptr< ::cbf_simulation::state_msg > state_msgPtr;
typedef boost::shared_ptr< ::cbf_simulation::state_msg const> state_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cbf_simulation::state_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cbf_simulation::state_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cbf_simulation::state_msg_<ContainerAllocator1> & lhs, const ::cbf_simulation::state_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cbf_simulation::state_msg_<ContainerAllocator1> & lhs, const ::cbf_simulation::state_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cbf_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cbf_simulation::state_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cbf_simulation::state_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cbf_simulation::state_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cbf_simulation::state_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cbf_simulation::state_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cbf_simulation::state_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cbf_simulation::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc3231566688c318ac8a6b339b1693c0";
  }

  static const char* value(const ::cbf_simulation::state_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc3231566688c318ULL;
  static const uint64_t static_value2 = 0xac8a6b339b1693c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cbf_simulation::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cbf_simulation/state_msg";
  }

  static const char* value(const ::cbf_simulation::state_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cbf_simulation::state_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 id \n"
"float64 x\n"
"float64 y\n"
"float64 vx\n"
"float64 vy\n"
;
  }

  static const char* value(const ::cbf_simulation::state_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cbf_simulation::state_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.vx);
      stream.next(m.vy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cbf_simulation::state_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cbf_simulation::state_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CBF_SIMULATION_MESSAGE_STATE_MSG_H
