# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cbf_simulation/cbf_data.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class cbf_data(genpy.Message):
  _md5sum = "c9f6db06237f3b61c11f2d3385758187"
  _type = "cbf_simulation/cbf_data"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
float64 px
float64 py
float64 vx
float64 vy
float64 ux_nom
float64 uy_nom
float64 ux_safe
float64 uy_safe"""
  __slots__ = ['stamp','px','py','vx','vy','ux_nom','uy_nom','ux_safe','uy_safe']
  _slot_types = ['time','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,px,py,vx,vy,ux_nom,uy_nom,ux_safe,uy_safe

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(cbf_data, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.px is None:
        self.px = 0.
      if self.py is None:
        self.py = 0.
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.ux_nom is None:
        self.ux_nom = 0.
      if self.uy_nom is None:
        self.uy_nom = 0.
      if self.ux_safe is None:
        self.ux_safe = 0.
      if self.uy_safe is None:
        self.uy_safe = 0.
    else:
      self.stamp = genpy.Time()
      self.px = 0.
      self.py = 0.
      self.vx = 0.
      self.vy = 0.
      self.ux_nom = 0.
      self.uy_nom = 0.
      self.ux_safe = 0.
      self.uy_safe = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I8d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.px, _x.py, _x.vx, _x.vy, _x.ux_nom, _x.uy_nom, _x.ux_safe, _x.uy_safe))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.stamp.secs, _x.stamp.nsecs, _x.px, _x.py, _x.vx, _x.vy, _x.ux_nom, _x.uy_nom, _x.ux_safe, _x.uy_safe,) = _get_struct_2I8d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I8d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.px, _x.py, _x.vx, _x.vy, _x.ux_nom, _x.uy_nom, _x.ux_safe, _x.uy_safe))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.stamp.secs, _x.stamp.nsecs, _x.px, _x.py, _x.vx, _x.vy, _x.ux_nom, _x.uy_nom, _x.ux_safe, _x.uy_safe,) = _get_struct_2I8d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I8d = None
def _get_struct_2I8d():
    global _struct_2I8d
    if _struct_2I8d is None:
        _struct_2I8d = struct.Struct("<2I8d")
    return _struct_2I8d
